version: '3.1'

services:
  web:
    image: nginx:latest
    container_name: project-docker-compose
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./teste-frenet:/var/www/html/site
